"""add online exam models

Revision ID: 4c93390b9542
Revises: b97456fa9166
Create Date: 2026-04-08 21:00:50.869071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c93390b9542'
down_revision = 'b97456fa9166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=30), nullable=False),
    sa.Column('end_time', sa.String(length=30), nullable=False),
    sa.Column('display_mode', sa.String(length=20), nullable=False),
    sa.Column('save_mode', sa.String(length=20), nullable=False),
    sa.Column('randomize', sa.Boolean(), nullable=True),
    sa.Column('show_result', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['student_groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'student_id', name='uq_group_student')
    )
    op.create_table('exam_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assigned_via', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_session_student')
    )
    op.create_table('exam_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.String(length=30), nullable=True),
    sa.Column('submitted_at', sa.String(length=30), nullable=True),
    sa.Column('question_order', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_attempt_session_student')
    )
    op.create_table('online_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_choice_id', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['choices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_answer_attempt_question')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('online_answers')
    op.drop_table('exam_attempts')
    op.drop_table('exam_assignments')
    op.drop_table('student_group_members')
    op.drop_table('exam_sessions')
    op.drop_table('student_groups')
    # ### end Alembic commands ###
