"""add proctoring models and columns

Revision ID: e2d10c84449e
Revises: 4c93390b9542
Create Date: 2026-04-08 21:53:25.490728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d10c84449e'
down_revision = '4c93390b9542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctor_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctor_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['proctor_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('warning_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proctoring_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lockdown_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cheat_response', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('warning_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_column('warning_threshold')
        batch_op.drop_column('cheat_response')
        batch_op.drop_column('lockdown_enabled')
        batch_op.drop_column('proctoring_enabled')

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_column('warning_count')
        batch_op.drop_column('flagged')

    op.drop_table('proctor_events')
    op.drop_table('proctor_snapshots')
    op.drop_table('capture_requests')
    # ### end Alembic commands ###
